openapi: 3.0.0
info:
  title: Nutrify API
  version: 1.0.0
  description: API para gerenciamento de alimentação, dieta e controle de calorias
servers:
  - url: http://localhost:3000
paths:
  /users/register:
    post:
      summary: Registro de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuário registrado
  /users/login:
    post:
      summary: Login de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token JWT
  /users/profile:
    get:
      summary: Perfil do usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dados do usuário
  /foods:
    post:
      summary: Cadastrar alimento
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Food'
      responses:
        '201':
          description: Alimento criado
    get:
      summary: Listar alimentos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de alimentos
  /foods/{id}:
    put:
      summary: Atualizar alimento
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Food'
      responses:
        '200':
          description: Alimento atualizado
    delete:
      summary: Remover alimento
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Alimento removido
  /meals:
    post:
      summary: Registrar refeição
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
      responses:
        '201':
          description: Refeição registrada
    get:
      summary: Listar refeições do usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de refeições
  /meals/{id}:
    put:
      summary: Atualizar refeição
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
      responses:
        '200':
          description: Refeição atualizada
    delete:
      summary: Remover refeição
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Refeição removida
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Food:
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        calories:
          type: number
        protein:
          type: number
        carbs:
          type: number
        fat:
          type: number
    Meal:
      type: object
      properties:
        date:
          type: string
          format: date-time
        foods:
          type: array
          items:
            type: string
        totalCalories:
          type: number
        totalProtein:
          type: number
        totalCarbs:
          type: number
        totalFat:
          type: number
